# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.BigIntegerField()),
                ('respondent', models.BigIntegerField()),
                ('paillier_n', models.CharField(max_length=4096)),
                ('paillier_g', models.CharField(max_length=4096)),
                ('ope_key', models.CharField(max_length=4096)),
                ('weight', models.CharField(max_length=4096)),
                ('settings', models.CharField(max_length=4096)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('request', 'respondent')]),
        ),
    ]
