# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunicationServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='spa_policies',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
