# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 05:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('start_time', models.TimeField(default=datetime.datetime(2016, 1, 13, 5, 58, 6, 971523))),
            ],
        ),
    ]
