# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MergeServer', '0002_auto_20160113_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='requester',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='values',
            field=models.TextField(default='as'),
            preserve_default=False,
        ),
    ]
