# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 07:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MergeServer', '0003_auto_20160113_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
