# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MergeServer', '0004_auto_20160113_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='n_square',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='settings',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='spa_policies',
            field=models.CharField(default='', max_length=4096),
            preserve_default=False,
        ),
    ]
